services:
  - type: web
    name: protrader-terminal
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true
    envVars:
      - key: ALPACA_KEY
        sync: false
      - key: ALPACA_SECRET
        sync: false
      - key: GEMINI_KEY
        sync: false
      - key: GEMINI_SECRET
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
